"""Added Notification data

Revision ID: f120f5eaf107
Revises: 7c2b0d5892e3
Create Date: 2024-12-12 16:14:02.638889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f120f5eaf107'
down_revision: Union[str, None] = '7c2b0d5892e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_location', sa.String(), nullable=False),
    sa.Column('end_location', sa.String(), nullable=False),
    sa.Column('flight_number', sa.String(), nullable=False),
    sa.Column('departure_date_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_date_time', sa.DateTime(), nullable=False),
    sa.Column('flight_duration', sa.String(), nullable=False),
    sa.Column('departure_location', sa.String(), nullable=False),
    sa.Column('arrival_location', sa.String(), nullable=False),
    sa.Column('price', sa.Double(), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_master_id'), 'flights_master', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('phone_no', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_flights_master_id'), table_name='flights_master')
    op.drop_table('flights_master')
    # ### end Alembic commands ###
